### ISSUE TITLE
Users cannot modify template files

### ISSUE THREAD

**Issue by Jollywatt** [spidersouris/touying-unistra-pristine#1]
The readme says to edit the settings.typ file to configure some package settings, such as language. Users cannot do this without first cloning the package, defeating the purpose of its use as a package imported with
```typ
#import "@preview/touying-unistra-pristine:1.1.0": *
```
You should reorganise the settings so that they are configurable by the user.

(Some things, such as the default language, should probably not be set by the package at all.)

**Comment by spidersouris** [comment]
Thanks — I had indeed noticed it soon after publishing on Typst Universe but I never took the time to refactor the whole thing. Hopefully https://github.com/spidersouris/touying-unistra-pristine/commit/fb07f70b482cc03952abda6fa900e722797ea99d should help with this. I need to test it a bit more, and when fully ready, I'll update the README.

**Comment by spidersouris** [comment]
Fixed and released with [v1.2.0](https://github.com/spidersouris/touying-unistra-pristine/releases/tag/v1.2.0).
